In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [7]:
#2. Print the NUMPY version and the configuration.
print(np.version.version)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
None


In [45]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.randint(1,10,[2,3,5])

In [46]:
#4. Print a.
print(a)

[[[8 2 7 9 8]
  [5 4 1 8 9]
  [5 7 6 4 1]]

 [[2 8 4 9 4]
  [7 9 8 4 5]
  [3 3 2 6 2]]]


In [47]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3))

In [48]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [62]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.shape)
print(b.shape)

if a.shape == b.shape:
    print('True')
else:
    print('False')


(2, 3, 5)
(5, 2, 3)
False


In [63]:
#8. Are you able to add a and b? Why or why not? No, because the shape is not the same size (a=2, b=5)
add_ab = np.add(a, b)
add_ab

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [55]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.reshape(2,3,5)
print(c)



[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [70]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now? Because the shape is the same size
d = np.add(a, c)
print(d)


[[[ 9.  3.  8. 10.  9.]
  [ 6.  5.  2.  9. 10.]
  [ 6.  8.  7.  5.  2.]]

 [[ 3.  9.  5. 10.  5.]
  [ 8. 10.  9.  5.  6.]
  [ 4.  4.  3.  7.  3.]]]


In [39]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a, d)

[[[0.39901022 0.15018532 0.98816898 0.32933761 0.53227135]
  [0.43541379 0.58660555 0.98699552 0.60084948 0.14564735]
  [0.19985967 0.0541933  0.02532034 0.34054226 0.23540739]]

 [[0.12834185 0.4510112  0.36337725 0.38068902 0.32634315]
  [0.30432065 0.29576045 0.34579448 0.90921226 0.48603717]
  [0.84603623 0.60270707 0.19376072 0.30976601 0.68425369]]] [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [64]:
#12. Multiply a and c. Assign the result to e.
e = a*c
e

array([[[8., 2., 7., 9., 8.],
        [5., 4., 1., 8., 9.],
        [5., 7., 6., 4., 1.]],

       [[2., 8., 4., 9., 4.],
        [7., 9., 8., 4., 5.],
        [3., 3., 2., 6., 2.]]])

In [66]:
#13. Does e equal to a? Why or why not? Yes, because the shape are the same size.
print(a.shape)
print(e.shape)

if a.shape == e.shape:
    print('true')
else:
        print('false')

(2, 3, 5)
(2, 3, 5)
true


In [69]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

10.0
2.0
6.333333333333333


In [81]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty(np.shape(d))
print (f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
