In [1]:
import numpy as np

In [2]:
print(np.version.version)

1.18.1


In [3]:
a = np.random.random((2,4,5))

In [4]:
a

array([[[0.9329845 , 0.128101  , 0.9959487 , 0.24893868, 0.66483033],
        [0.23502841, 0.47124833, 0.91969267, 0.07235417, 0.36104297],
        [0.25271899, 0.1186813 , 0.01383561, 0.39026712, 0.54340306],
        [0.72037901, 0.10107357, 0.64204159, 0.06710789, 0.63325047]],

       [[0.49580425, 0.25264124, 0.87853045, 0.5972728 , 0.39760604],
        [0.01200639, 0.47060726, 0.19327486, 0.16813585, 0.00499401],
        [0.83336983, 0.67494004, 0.29088439, 0.53672004, 0.00818617],
        [0.26447055, 0.75374309, 0.71532755, 0.28643655, 0.28649459]]])

In [5]:
b = np.ones((5,4,2))

In [6]:
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [7]:
b.shape == a.shape

False

In [8]:
a + b

ValueError: operands could not be broadcast together with shapes (2,4,5) (5,4,2) 

In [9]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,4,5) (5,4,2) 

## Is not posible because they dont have the same number of elements.

In [10]:
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [11]:
c = b.T

In [12]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [13]:
d = np.add(a,c)

In [14]:
d

array([[[1.9329845 , 1.128101  , 1.9959487 , 1.24893868, 1.66483033],
        [1.23502841, 1.47124833, 1.91969267, 1.07235417, 1.36104297],
        [1.25271899, 1.1186813 , 1.01383561, 1.39026712, 1.54340306],
        [1.72037901, 1.10107357, 1.64204159, 1.06710789, 1.63325047]],

       [[1.49580425, 1.25264124, 1.87853045, 1.5972728 , 1.39760604],
        [1.01200639, 1.47060726, 1.19327486, 1.16813585, 1.00499401],
        [1.83336983, 1.67494004, 1.29088439, 1.53672004, 1.00818617],
        [1.26447055, 1.75374309, 1.71532755, 1.28643655, 1.28649459]]])

In [15]:
e = a*c

In [16]:
e

array([[[0.9329845 , 0.128101  , 0.9959487 , 0.24893868, 0.66483033],
        [0.23502841, 0.47124833, 0.91969267, 0.07235417, 0.36104297],
        [0.25271899, 0.1186813 , 0.01383561, 0.39026712, 0.54340306],
        [0.72037901, 0.10107357, 0.64204159, 0.06710789, 0.63325047]],

       [[0.49580425, 0.25264124, 0.87853045, 0.5972728 , 0.39760604],
        [0.01200639, 0.47060726, 0.19327486, 0.16813585, 0.00499401],
        [0.83336983, 0.67494004, 0.29088439, 0.53672004, 0.00818617],
        [0.26447055, 0.75374309, 0.71532755, 0.28643655, 0.28649459]]])

In [17]:
a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

## Is equal

In [18]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [19]:
d_max

1.9959486996387859

In [20]:
d_min

1.0049940079178756

In [21]:
d_mean

1.4158593585084822

In [22]:
d

array([[[1.9329845 , 1.128101  , 1.9959487 , 1.24893868, 1.66483033],
        [1.23502841, 1.47124833, 1.91969267, 1.07235417, 1.36104297],
        [1.25271899, 1.1186813 , 1.01383561, 1.39026712, 1.54340306],
        [1.72037901, 1.10107357, 1.64204159, 1.06710789, 1.63325047]],

       [[1.49580425, 1.25264124, 1.87853045, 1.5972728 , 1.39760604],
        [1.01200639, 1.47060726, 1.19327486, 1.16813585, 1.00499401],
        [1.83336983, 1.67494004, 1.29088439, 1.53672004, 1.00818617],
        [1.26447055, 1.75374309, 1.71532755, 1.28643655, 1.28649459]]])

In [25]:
f = np.empty((2,4,5))

In [26]:
for i in range(len(d)):
    for j in range(len(d[1])):
        for k in range(len(d[0][0])):
            if d [i][j][k] > d_min and d [i][j][k] < d_mean:
                f [i][j][k] = 25
            elif d [i][j][k] > d_mean and d [i][j][k] < d_max:
                f [i][j][k] = 75
            elif d [i][j][k] == d_mean:
                f [i][j][k] = 50
            elif d [i][j][k] == d_min:
                f [i][j][k] = 0
            else: 
                f [i][j][k] = 100

In [27]:
f

array([[[ 75.,  25., 100.,  25.,  75.],
        [ 25.,  75.,  75.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  75.],
        [ 75.,  25.,  75.,  25.,  75.]],

       [[ 75.,  25.,  75.,  75.,  25.],
        [ 25.,  75.,  25.,  25.,   0.],
        [ 75.,  75.,  25.,  75.,  25.],
        [ 25.,  75.,  75.,  25.,  25.]]])

In [28]:
e = np.array(f).tolist()


In [29]:
e

[[[75.0, 25.0, 100.0, 25.0, 75.0],
  [25.0, 75.0, 75.0, 25.0, 25.0],
  [25.0, 25.0, 25.0, 25.0, 75.0],
  [75.0, 25.0, 75.0, 25.0, 75.0]],
 [[75.0, 25.0, 75.0, 75.0, 25.0],
  [25.0, 75.0, 25.0, 25.0, 0.0],
  [75.0, 75.0, 25.0, 75.0, 25.0],
  [25.0, 75.0, 75.0, 25.0, 25.0]]]

In [32]:
for i in range(len(d)):
    for j in range(len(d[1])):
        for k in range(len(d[0][0])):
            if d [i][j][k] > d_min and d [i][j][k] < d_mean:
                e [i][j][k] = "M"
            elif d [i][j][k] > d_mean and d [i][j][k] < d_max:
                e [i][j][k] = "N"
            elif d [i][j][k] == d_mean:
                e [i][j][k] = "Q"
            elif d [i][j][k] == d_min:
                e [i][j][k] = "F"
            else: 
                e [i][j][k] = "W"

In [33]:
e

[[['N', 'M', 'W', 'M', 'N'],
  ['M', 'N', 'N', 'M', 'M'],
  ['M', 'M', 'M', 'M', 'N'],
  ['N', 'M', 'N', 'M', 'N']],
 [['N', 'M', 'N', 'N', 'M'],
  ['M', 'N', 'M', 'M', 'F'],
  ['N', 'N', 'M', 'N', 'M'],
  ['M', 'N', 'N', 'M', 'M']]]