In [9]:
import numpy as np

In [10]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/joel/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/joel/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/joel/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/joel/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/joel/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/joel/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/joel/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/joel/opt/anaconda3/include']
None


In [11]:
a = np.random.random((2,3,5))
a

array([[[0.18989715, 0.60108223, 0.08910765, 0.22960338, 0.52578829],
        [0.16886485, 0.32792292, 0.96549896, 0.3481273 , 0.14686508],
        [0.18970577, 0.82259311, 0.56334472, 0.2160091 , 0.5624034 ]],

       [[0.83110534, 0.94293903, 0.79586415, 0.82648328, 0.89138811],
        [0.79229338, 0.81391056, 0.55057009, 0.46132053, 0.75065268],
        [0.80801964, 0.19035054, 0.63495439, 0.31419621, 0.03720095]]])

In [12]:
a_2 = np.random.randint(0, 100, size=(2, 3, 5))
a_2

array([[[57, 36, 90, 35, 62],
        [69, 10,  5, 96, 26],
        [84, 72,  8, 41, 89]],

       [[ 9,  6,  6, 64, 49],
        [86, 45, 56, 78, 80],
        [47,  6, 56, 90, 37]]])

In [13]:
a_3=np.random.randn(2,3,5) 
a_3

array([[[-0.29343149,  0.18431771,  0.54908231,  2.23624904,
          0.56711313],
        [ 0.86302418,  1.97962944,  0.05001629, -0.02691619,
         -0.97826562],
        [ 0.03176826,  0.31864565, -0.08413129,  0.5745066 ,
          1.03718688]],

       [[-2.56485319,  0.45545837, -1.10011753, -0.71825472,
         -0.01825602],
        [ 0.44189584, -1.64277485, -1.1977693 ,  1.18735027,
          0.1107258 ],
        [ 1.14826094, -0.72773848,  0.95040741, -0.55047481,
          0.09023399]]])

In [14]:
b = np.full(shape=(5, 2, 3), fill_value = 1)
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [15]:
a.ndim == b.ndim #yes, cause the arrays have the same amount of dimentions.

True

In [16]:
f = a+b
f
#No, beacause they need to have exactly the same amount of dimensions

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [17]:
c = b.reshape(2,3,5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [18]:
d = a+c
d
#it works becuase the have the same amount of dimentions

array([[[1.18989715, 1.60108223, 1.08910765, 1.22960338, 1.52578829],
        [1.16886485, 1.32792292, 1.96549896, 1.3481273 , 1.14686508],
        [1.18970577, 1.82259311, 1.56334472, 1.2160091 , 1.5624034 ]],

       [[1.83110534, 1.94293903, 1.79586415, 1.82648328, 1.89138811],
        [1.79229338, 1.81391056, 1.55057009, 1.46132053, 1.75065268],
        [1.80801964, 1.19035054, 1.63495439, 1.31419621, 1.03720095]]])

In [19]:
print(a)
print(d)

[[[0.18989715 0.60108223 0.08910765 0.22960338 0.52578829]
  [0.16886485 0.32792292 0.96549896 0.3481273  0.14686508]
  [0.18970577 0.82259311 0.56334472 0.2160091  0.5624034 ]]

 [[0.83110534 0.94293903 0.79586415 0.82648328 0.89138811]
  [0.79229338 0.81391056 0.55057009 0.46132053 0.75065268]
  [0.80801964 0.19035054 0.63495439 0.31419621 0.03720095]]]
[[[1.18989715 1.60108223 1.08910765 1.22960338 1.52578829]
  [1.16886485 1.32792292 1.96549896 1.3481273  1.14686508]
  [1.18970577 1.82259311 1.56334472 1.2160091  1.5624034 ]]

 [[1.83110534 1.94293903 1.79586415 1.82648328 1.89138811]
  [1.79229338 1.81391056 1.55057009 1.46132053 1.75065268]
  [1.80801964 1.19035054 1.63495439 1.31419621 1.03720095]]]


In [20]:
e=a*c
e

array([[[0.18989715, 0.60108223, 0.08910765, 0.22960338, 0.52578829],
        [0.16886485, 0.32792292, 0.96549896, 0.3481273 , 0.14686508],
        [0.18970577, 0.82259311, 0.56334472, 0.2160091 , 0.5624034 ]],

       [[0.83110534, 0.94293903, 0.79586415, 0.82648328, 0.89138811],
        [0.79229338, 0.81391056, 0.55057009, 0.46132053, 0.75065268],
        [0.80801964, 0.19035054, 0.63495439, 0.31419621, 0.03720095]]])

In [21]:
a==e
#because c only contains values, it multiplies for everything

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [22]:
d_max=np.amax(d)
d_min=np.amin(d)
d_mean=np.mean(d)

In [23]:
print(d_max)
print(d_min)
print(d_mean)

1.965498961824664
1.037200954774768
1.5196020935035892


In [24]:
f=np.zeros_like(d)
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [54]:
for a in range(0,2):
     for b in range(0,3):
        for c in range(0,5):
             if d[a,b,c] > d_min and d[a,b,c] < d_mean:
                f[a,b,c] = 25
             elif d[a,b,c] >d_mean and d[a,b,c] < d_max:
                f[a,b,c] = 75
             elif d[a,b,c] == d_mean:
                f[a,b,c] = 50
             elif d[a,b,c] == d_min:
                f[a,b,c] = 0
             elif d[a,b,c] == d_max:
                f[a,b,c] = 100

In [34]:
print(f)

[[[ 25.  75.  25.  25.  75.]
  [ 25.  25. 100.  25.  25.]
  [ 25.  75.  75.  25.  75.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  25.  75.]
  [ 75.  25.  75.  25.   0.]]]


In [58]:
f_2=f.astype(str)
for a in range(0,2):
    for b in range(0,3):
        for c in range(0,5):
            if d[a,b,c] > d_min and d[a,b,c] < d_mean:
                 f[a,b,c] = 'B'
            elif d[a,b,c] >d_mean and d[a,b,c] <d_max:
                 f[a,b,c] = 'D'
            elif d[a,b,c] == d_mean:
                 f[a,b,c] = 'C'
            elif d[a,b,c] == d_min:
                 f[a,b,c] = 'A'
            elif d[a,b,c] == d_max:
                 f[a,b,c] = 'E'
print(f_2)

ValueError: could not convert string to float: 'B'