In [1]:
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/HP/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a=np.random.random((2,3,5)) 
a_1=np.random.randint(0,100,(2,3,5)) 
a_2=np.random.randn(2,3,5)
#4. Print a.

a

array([[[0.21131213, 0.88292053, 0.13576669, 0.85987604, 0.19867795],
        [0.8895693 , 0.30423536, 0.39233909, 0.7870865 , 0.2135064 ],
        [0.59819855, 0.78472631, 0.60828345, 0.50960867, 0.01747648]],

       [[0.10427436, 0.61962484, 0.07695104, 0.16120951, 0.91243917],
        [0.02291434, 0.45493269, 0.42932419, 0.29982501, 0.95773231],
        [0.54708115, 0.68570748, 0.06262431, 0.92576411, 0.71147757]]])

In [4]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.full(shape=(5, 2, 3), fill_value = 1)
#6. Print b.

b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [5]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.ndim==b.ndim

True

In [6]:
#8. Are you able to add a and b? Why or why not?
#No, porque los arrays no tienen las mismas dimensiones.

In [7]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.reshape(2,3,5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [8]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d=a+c
d

#Porque ya tienen la misma dimensión

array([[[1.21131213, 1.88292053, 1.13576669, 1.85987604, 1.19867795],
        [1.8895693 , 1.30423536, 1.39233909, 1.7870865 , 1.2135064 ],
        [1.59819855, 1.78472631, 1.60828345, 1.50960867, 1.01747648]],

       [[1.10427436, 1.61962484, 1.07695104, 1.16120951, 1.91243917],
        [1.02291434, 1.45493269, 1.42932419, 1.29982501, 1.95773231],
        [1.54708115, 1.68570748, 1.06262431, 1.92576411, 1.71147757]]])

In [9]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print('a=', a)
print('d=', d)

#Hay un arreglo de diferencia porque sólo agregamos los valores

a= [[[0.21131213 0.88292053 0.13576669 0.85987604 0.19867795]
  [0.8895693  0.30423536 0.39233909 0.7870865  0.2135064 ]
  [0.59819855 0.78472631 0.60828345 0.50960867 0.01747648]]

 [[0.10427436 0.61962484 0.07695104 0.16120951 0.91243917]
  [0.02291434 0.45493269 0.42932419 0.29982501 0.95773231]
  [0.54708115 0.68570748 0.06262431 0.92576411 0.71147757]]]
d= [[[1.21131213 1.88292053 1.13576669 1.85987604 1.19867795]
  [1.8895693  1.30423536 1.39233909 1.7870865  1.2135064 ]
  [1.59819855 1.78472631 1.60828345 1.50960867 1.01747648]]

 [[1.10427436 1.61962484 1.07695104 1.16120951 1.91243917]
  [1.02291434 1.45493269 1.42932419 1.29982501 1.95773231]
  [1.54708115 1.68570748 1.06262431 1.92576411 1.71147757]]]


In [10]:
#12. Multiply a and c. Assign the result to e.
e = a*c
e

array([[[0.21131213, 0.88292053, 0.13576669, 0.85987604, 0.19867795],
        [0.8895693 , 0.30423536, 0.39233909, 0.7870865 , 0.2135064 ],
        [0.59819855, 0.78472631, 0.60828345, 0.50960867, 0.01747648]],

       [[0.10427436, 0.61962484, 0.07695104, 0.16120951, 0.91243917],
        [0.02291434, 0.45493269, 0.42932419, 0.29982501, 0.95773231],
        [0.54708115, 0.68570748, 0.06262431, 0.92576411, 0.71147757]]])

In [11]:
#13. Does e equal to a? Why or why not?
e == a
#Porque se multiplica cada elemento por todo

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [12]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print('d_max:', d_max)
print('d_min:', d_min)
print('d_mean:', d_mean)

d_max: 1.9577323121031247
d_min: 1.0174764802768022
d_mean: 1.4788488509620399


In [13]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2, 3, 5), dtype=float)
f

array([[[0.21131213, 0.88292053, 0.13576669, 0.85987604, 0.19867795],
        [0.8895693 , 0.30423536, 0.39233909, 0.7870865 , 0.2135064 ],
        [0.59819855, 0.78472631, 0.60828345, 0.50960867, 0.01747648]],

       [[0.10427436, 0.61962484, 0.07695104, 0.16120951, 0.91243917],
        [0.02291434, 0.45493269, 0.42932419, 0.29982501, 0.95773231],
        [0.54708115, 0.68570748, 0.06262431, 0.92576411, 0.71147757]]])

In [15]:

"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

for i in np.nditer(d):
    if i == d_min:
        f = 0
    elif [(i>d_min) & (i<d_mean)]:
        f = 25
    elif i==d_mean:
        f = 50
    elif [(i < d_max) & (i > d_mean)]:
        f = 75
    elif i == d_max:
        f = 100
print(f)


25


In [16]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


f_2=f.astype(str)
for a in range(0,2):
    for b in range(0,3):
        for c in range(0,5):
            if d[a,b,c] > d_min and d[a,b,c] < d_mean:
                 f[a,b,c] = 'B'
            elif d[a,b,c] >d_mean and d[a,b,c] <d_max:
                 f[a,b,c] = 'D'
            elif d[a,b,c] == d_mean:
                 f[a,b,c] = 'C'
            elif d[a,b,c] == d_min:
                 f[a,b,c] = 'A'
            elif d[a,b,c] == d_max:
                 f[a,b,c] = 'E'

AttributeError: 'int' object has no attribute 'astype'