In [2]:
import numpy as np

In [3]:
print (np.version.version)

1.18.1


In [4]:
a = np.random.random((2,4,5))

In [5]:
a

array([[[0.96240124, 0.69257001, 0.61204961, 0.46382771, 0.95920753],
        [0.05398043, 0.589886  , 0.49829508, 0.29219754, 0.2933152 ],
        [0.62961794, 0.87063866, 0.45414157, 0.80041504, 0.08139007],
        [0.5128348 , 0.9843796 , 0.18455971, 0.24022739, 0.95143458]],

       [[0.22985078, 0.0607904 , 0.33054058, 0.07504005, 0.40502492],
        [0.23807072, 0.43535535, 0.12904614, 0.9568874 , 0.3111717 ],
        [0.07901322, 0.8099356 , 0.02383542, 0.40724714, 0.16120734],
        [0.18387223, 0.01179518, 0.53250102, 0.39129051, 0.72766563]]])

In [6]:
b = np.ones((5,4,2))

In [7]:
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [8]:
b.shape == a.shape

False

In [9]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,4,5) (5,4,2) 

In [10]:
#Algebraicamente, la suma de matrices es aceptable solo entre matrices del mismo tamaño. 

In [11]:
c = b.T

In [12]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [13]:
d = np.add(a,c)

In [14]:
d

array([[[1.96240124, 1.69257001, 1.61204961, 1.46382771, 1.95920753],
        [1.05398043, 1.589886  , 1.49829508, 1.29219754, 1.2933152 ],
        [1.62961794, 1.87063866, 1.45414157, 1.80041504, 1.08139007],
        [1.5128348 , 1.9843796 , 1.18455971, 1.24022739, 1.95143458]],

       [[1.22985078, 1.0607904 , 1.33054058, 1.07504005, 1.40502492],
        [1.23807072, 1.43535535, 1.12904614, 1.9568874 , 1.3111717 ],
        [1.07901322, 1.8099356 , 1.02383542, 1.40724714, 1.16120734],
        [1.18387223, 1.01179518, 1.53250102, 1.39129051, 1.72766563]]])

In [15]:
e = a*c

In [16]:
e

array([[[0.96240124, 0.69257001, 0.61204961, 0.46382771, 0.95920753],
        [0.05398043, 0.589886  , 0.49829508, 0.29219754, 0.2933152 ],
        [0.62961794, 0.87063866, 0.45414157, 0.80041504, 0.08139007],
        [0.5128348 , 0.9843796 , 0.18455971, 0.24022739, 0.95143458]],

       [[0.22985078, 0.0607904 , 0.33054058, 0.07504005, 0.40502492],
        [0.23807072, 0.43535535, 0.12904614, 0.9568874 , 0.3111717 ],
        [0.07901322, 0.8099356 , 0.02383542, 0.40724714, 0.16120734],
        [0.18387223, 0.01179518, 0.53250102, 0.39129051, 0.72766563]]])

In [17]:
a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [64]:
ºxºdf.min()

NameError: name 'df' is not defined

In [63]:
d_min = d.min()
print(d_min)

1.0117951847139288


In [34]:
d_max = d.max()
print(d_max)

1.9843795951772734


In [42]:
d_mean = d.mean()
print(d_mean)

1.4406877763283776


In [46]:
f = np.empty((2,4,5))

In [47]:
f

array([[[0.96240124, 0.69257001, 0.61204961, 0.46382771, 0.95920753],
        [0.05398043, 0.589886  , 0.49829508, 0.29219754, 0.2933152 ],
        [0.62961794, 0.87063866, 0.45414157, 0.80041504, 0.08139007],
        [0.5128348 , 0.9843796 , 0.18455971, 0.24022739, 0.95143458]],

       [[0.22985078, 0.0607904 , 0.33054058, 0.07504005, 0.40502492],
        [0.23807072, 0.43535535, 0.12904614, 0.9568874 , 0.3111717 ],
        [0.07901322, 0.8099356 , 0.02383542, 0.40724714, 0.16120734],
        [0.18387223, 0.01179518, 0.53250102, 0.39129051, 0.72766563]]])

In [48]:
for i in range(len(d)):
    for j in range(len(d[1])):
        for k in range(len(d[0][0])):
            if d [i][j][k] > d_min and d [i][j][k] < d_mean:
                f [i][j][k] = 25
            elif d [i][j][k] > d_mean and d [i][j][k] < d_max:
                f [i][j][k] = 75
            elif d [i][j][k] == d_mean:
                f [i][j][k] = 50
            elif d [i][j][k] == d_min:
                f [i][j][k] = 0
            else: 
                f [i][j][k] = 100

In [49]:
f

array([[[ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,  75.,  25.,  25.],
        [ 75.,  75.,  75.,  75.,  25.],
        [ 75., 100.,  25.,  25.,  75.]],

       [[ 25.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,  75.,  25.],
        [ 25.,  75.,  25.,  25.,  25.],
        [ 25.,   0.,  75.,  25.,  75.]]])

In [50]:
d

array([[[1.96240124, 1.69257001, 1.61204961, 1.46382771, 1.95920753],
        [1.05398043, 1.589886  , 1.49829508, 1.29219754, 1.2933152 ],
        [1.62961794, 1.87063866, 1.45414157, 1.80041504, 1.08139007],
        [1.5128348 , 1.9843796 , 1.18455971, 1.24022739, 1.95143458]],

       [[1.22985078, 1.0607904 , 1.33054058, 1.07504005, 1.40502492],
        [1.23807072, 1.43535535, 1.12904614, 1.9568874 , 1.3111717 ],
        [1.07901322, 1.8099356 , 1.02383542, 1.40724714, 1.16120734],
        [1.18387223, 1.01179518, 1.53250102, 1.39129051, 1.72766563]]])

In [57]:
g = np.array(f).tolist()
g

[[[75.0, 75.0, 75.0, 75.0, 75.0],
  [25.0, 75.0, 75.0, 25.0, 25.0],
  [75.0, 75.0, 75.0, 75.0, 25.0],
  [75.0, 100.0, 25.0, 25.0, 75.0]],
 [[25.0, 25.0, 25.0, 25.0, 25.0],
  [25.0, 25.0, 25.0, 75.0, 25.0],
  [25.0, 75.0, 25.0, 25.0, 25.0],
  [25.0, 0.0, 75.0, 25.0, 75.0]]]

In [59]:
for i in range(len(d)):
    for j in range(len(d[1])):
        for k in range(len(d[0][0])):
            if d [i][j][k] > d_min and d [i][j][k] < d_mean:
                g [i][j][k] = "S"
            elif d [i][j][k] > d_mean and d [i][j][k] < d_max:
                g [i][j][k] = "D"
            elif d [i][j][k] == d_mean:
                g [i][j][k] = "F"
            elif d [i][j][k] == d_min:
                g [i][j][k] = "E"
            else: 
                g [i][j][k] = "R"

In [61]:
g

[[['D', 'D', 'D', 'D', 'D'],
  ['S', 'D', 'D', 'S', 'S'],
  ['D', 'D', 'D', 'D', 'S'],
  ['D', 'R', 'S', 'S', 'D']],
 [['S', 'S', 'S', 'S', 'S'],
  ['S', 'S', 'S', 'D', 'S'],
  ['S', 'D', 'S', 'S', 'S'],
  ['S', 'E', 'D', 'S', 'D']]]